repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
      - id: pretty-format-json
        args: ["--indent=4", "--autofix", "--no-sort-keys"]
      # - id: check-added-large-files

  - repo: local
    hooks:
      - id: format
        name: format
        description: Format files with rustfmt.
        entry: makers fmt
        language: system
        types: [rust]
        pass_filenames: false
      - id: lint
        name: lint
        description: Lint files with Clippy.
        entry: makers lint
        language: system
        types: [rust]
        pass_filenames: false
      - id: check
        name: check
        description: Check files with Cargo Check
        entry: cargo check
        language: system
        types: [rust]
        pass_filenames: false
