version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "securepassword"
      POSTGRES_DB: "benchmarks"
    volumes:
      - postgres-storage:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5532:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    restart: unless-stopped

  pgbouncer:
    image: rmccaffrey/pgbouncer:latest
    environment:
      - DATABASE_URL=postgres://admin:securepassword@postgres:5432/benchmarks
      - POOL_MODE=transaction
      - MAX_DB_CONNECTIONS=100
      - DEFAULT_POOL_SIZE=40
      - AUTH_TYPE=scram-sha-256
    depends_on:
      - postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres-storage:
