[tasks.setup]
script = '''
    echo # installing git hooks
    pre-commit --version || pip install pre-commit
    pre-commit install || echo "failed to install git hooks!" 1>&2
'''

[tasks.dev]
command = "cargo"
args = ["run"]
env_files = ["./.env"]
watch = true

[tasks.lint]
install_crate = "clippy-nightly"
command = "cargo"
args = [
	"+nightly",
	"clippy",
	"--tests",
	"--examples",
	"--all-targets",
	"--all-features",
	"--workspace",
]

[tasks.lint-ci]
install_crate = "clippy-nightly"
command = "cargo"
args = [
	"+nightly",
	"clippy",
	"--tests",
	"--examples",
	"--all-targets",
	"--all-features",
	"--workspace",
	"--",
	"-D",
	"warnings",
]

[tasks.format]
install_crate = "rustfmt-nightly"
command = "cargo"
args = ["+nightly", "fmt", "--all"]

[tasks.fmt]
alias = "format"

[tasks.format-ci]
install_crate = "rustfmt-nightly"
command = "cargo"
args = ["+nightly", "fmt", "--all", "--", "--check"]
